### ISSUE TITLE
Can't run dynoviz (OSError: 'seaborn' is not a valid package style)

### ISSUE THREAD

**Issue by hubertrybka** [wolberlab/dynophores#65]
Hi,

I just installed dynophores using conda.

When running `dynoviz -h` I get the following error message:

> Traceback (most recent call last):
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/matplotlib/style/core.py", line 137, in use
>     style = _rc_params_in_file(style)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
>     with _open_file_or_url(fname) as fd:
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/contextlib.py", line 137, in __enter__
>     return next(self.gen)
>            ^^^^^^^^^^^^^^
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
>     with open(fname, encoding='utf-8') as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/bmc/miniconda3/envs/dyno/bin/dynoviz", line 6, in <module>
>     from dynophores.cli import main
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/dynophores/__init__.py", line 8, in <module>
>     from .viz import plot, view2d, view3d
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/dynophores/viz/plot/__init__.py", line 6, in <module>
>     from . import static
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/dynophores/viz/plot/static.py", line 13, in <module>
>     plt.style.use("seaborn")
>   File "/home/bmc/miniconda3/envs/dyno/lib/python3.12/site-packages/matplotlib/style/core.py", line 139, in use
>     raise OSError(
> OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

System: Ubuntu 22.04.4 LTS

Thanks for helping me resolve this issue this issue!

**Comment by dominiquesydow** [comment]
Hi @hubertrybka,

Thanks for reporting this issue, will bring a fix on its way in a moment. 

This issue seems to stem from a deprecation in Matplotlib 3.8.0, where the style `seaborn` changed to `seaborn-v0_8`:
> Support for the `seaborn-<foo>` styles; use `seaborn-v0_8-<foo>` instead, or directly use the seaborn API.

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#removal-of-deprecated-apis

**Comment by dominiquesydow** [comment]
Reproduced issue in CI: https://github.com/wolberlab/dynophores/actions/runs/8850471029/job/24304829147

**Comment by dominiquesydow** [comment]
@hubertrybka, I made the changes as part of #66 and released the new 0.3.0 tag. I still need to cut a new conda release but will do that over the weekend.

**Comment by dominiquesydow** [comment]
Hi @hubertrybka, the new conda release is out :) 
https://anaconda.org/conda-forge/dynophores

I will close this issue now but please reopen it if needed. 
Many thanks again for bringing this to our attention!
